services:
  db:
    image: mysql:8.3.0
    container_name: security_db
    command: mysqld --default_authentication_plugin=mysql_native_password

    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: security
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: app_security
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308

    ports:
      - "3308:3308"
